# Aliases -- grouped by tool.

##################################################
# UTILITY

alias zshrc='nvim ~/.zshrc'
alias sz='source ~/.zshrc'

alias n='nvim'
alias h='history 1'
alias c='clear'
alias r='reset'
alias x='exit'
alias la='ls -a'
alias ll='ls -FGalh --color=auto'
alias ts='tree -CshF -L 2'
alias duh='du -h --max-depth=1'
alias dfh='df -h'
alias cp='cp -v'
alias rm='rm -i'
alias cgrep='grep -Hn --color=always'

##################################################
# DOCKER

alias dps='docker ps --all --format "table {{.ID}}\t{{.Names}}\t| {{.RunningFor}}\t{{.Status}}\t| {{.Ports}}"'
alias dsa='docker stop $(docker ps -aq)'
alias dra='docker rm $(docker ps -aq)'
alias drf='docker rm $(docker ps --all --quiet --filter "name=$@")'
alias dsp='docker system prune --all'
alias dspv='docker system prune --all --volumes'
alias dst='docker stats --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}"'
alias dlt='docker logs -f "$@"'

##################################################
# GIT

alias gu="gitui"
alias gs='git status'
alias ga='git add'
alias gap='git add -p'
alias gd='git diff'
alias gdc='git diff --compact-summary'
alias gc='git commit -m'
alias gl="git log --pretty=format:'%C(yellow)%h %Cred%ad %Cblue%an%Cgreen%d %Creset%s' --date=short"
alias grl="git reflog --date=local"
alias gco='git checkout $1'
alias gcb='git checkout -b $1'
alias gpu='git push'
alias gpd='git pull'
alias grm='git restore --staged'
alias gsps='git stash && git pull && git stash apply'

##################################################
# TMUX

alias tx='tmuxinator'
alias tls='tmux ls'
alias tns='tmux new -s $1'
alias tas='tmux attach-session -t $1'
alias tks='tmux kill-session -t $1'
alias tka='tmux kill-session -a'
