# Shell functions.

listport() {
    lsof -i :"$1"
}

killport() {
    kill $(lsof -t -i :"$1")
}

pretty_diff() {
    if command -v diff-so-fancy &>/dev/null; then
        git diff --color | diff-so-fancy
    else
        git diff --color-words
    fi
}

gclone() {
    git clone "git@github.com:$1/$2.git" "$3"
}
