# Shell options -- behavior, not appearance.

export EDITOR=nvim

# History
HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY
setopt APPEND_HISTORY

# Shell behavior
setopt AUTO_CD
setopt CORRECT
setopt INTERACTIVE_COMMENTS

# Vim mode
bindkey -v
export KEYTIMEOUT=1
